In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
clients = pd.read_csv('./data/trinet_clients.csv', parse_dates=True)
clients.head()

/Users/jamesrichards/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Company,Company.Name,City,State,Related.Company,Company.Live.Date,NAICS.2,NAICS.3,NAICS.4,...,Total.Voluntary.Employee.Terminations.2015,Total.Involuntary.Employee.Terminations.2014,Total.Involuntary.Employee.Terminations.2015,Avg.nps.201409.Other,Avg.nps.201409.Primary,Avg.nps.201503.Other,Avg.nps.201503.Primary,Avg.nps.201508.Other,Avg.nps.201508.Primary,nps.survey.2013
0,1,4AW,HRchitect Canada,Frisco,TX,NaN,1/12/2004,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,False
1,2,4B9,RouteOne - Canada,Farmington Hills,MI,NaN,2/16/2004,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4BJ,Ekaria LLP - Canada,Redmond,WA,495,1/1/2004,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,False
3,4,4BY,"MicroVention, Inc. - Canada",Aliso Viejo,CA,NaN,2/1/2004,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,False
4,5,51Z,Signature Control Systems CAN,Sheridan,CO,NaN,8/1/2006,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,True

In [3]:
clients.shape

(9677, 119)

In [8]:
clients.isnull().sum()

Unnamed: 0                                            0
Company                                               0
Company.Name                                          5
City                                                  0
State                                                 0
Related.Company                                    8050
Company.Live.Date                                     0
NAICS.2                                             139
NAICS.3                                             139
NAICS.4                                             139
NAICS.5                                             139
NAICS.6                                             139
NAICS.2.des                                         139
NAICS.3.des                                         148
NAICS.4.des                                         149
NAICS.5.des                                         151
NAICS.6.des                                         162
CSA                                                   0
HCC                                                   0
HCD                                                  14
RSC                                                 282
CSM                                                2299
Risk.Color                                         2535
WSE.Count.Dec.2014                                 3968
WSE.Count.Dec.2015                                    0
Sales.Industry                                      139
Sales.Sub.Industry                                  139
Expense                                               0
Hire                                                  0
Perform                                               0
                                                   ...
Interaction.Type.Count.Risk.Underwriting.2014         0
Interaction.Type.Count.Risk.Underwriting.2015         0
Interaction.Type.Count.Strategic.Services.2014        0
Interaction.Type.Count.Strategic.Services.2015        0
Interaction.Type.Count.Tax.Department.2015            0
Interaction.Type.Count.Unemployment.Claims.2014       0
Interaction.Type.Count.Unemployment.Claims.2015       0
Interaction.Type.Count.WC.Claims.2014                 0
Interaction.Type.Count.WC.Claims.2015                 0
Total.Survey.Completed.2014                           0
Total.Survey.Completed.2015                           0
Total.Survey.Pass.2014                             8249
Total.Survey.Pass.2015                             7594
Total.Survey.Fail.2014                             8765
Total.Survey.Fail.2015                             8257
Total.Payroll.Processed.2015                       1256
Total.Payroll.With.Errors.2015                     1256
Total.Employee.Terminations.2014                    953
Total.Employee.Terminations.2015                    953
Total.Voluntary.Employee.Terminations.2014          953
Total.Voluntary.Employee.Terminations.2015          953
Total.Involuntary.Employee.Terminations.2014        953
Total.Involuntary.Employee.Terminations.2015        953
Avg.nps.201409.Other                               9254
Avg.nps.201409.Primary                             8992
Avg.nps.201503.Other                               9238
Avg.nps.201503.Primary                             8996
Avg.nps.201508.Other                               9139
Avg.nps.201508.Primary                             8705
nps.survey.2013                                    7280
dtype: int64